#!/usr/bin/env perl
# Synopsis: Adjust timestamp in a srt file.
use strict;
use Getopt::Long;

my %scales =  ( 'h' => 3600000,
                'm' => 60000,
                's' => 1000,
                'u' => 1,
              );

my ($opt_t);
GetOptions ( "t=s" => \$opt_t, "time"      => \$opt_t,
           );

if ( $opt_t )
{
  my $sign  = substr($opt_t,0,1);
  my $scale = substr($opt_t,length($opt_t)-1, 1);
  my $time  = int(substr($opt_t,1,length($opt_t)-2));

  if ( $sign !~ /[+-]/ || $scale !~ /[hmsu]/ )
  {
    die "Time should be [+-]<secs><hmsu>";
  }

  if ( $scales{$scale} )
  {
    $time = $time * $scales{$scale};
  }

  if ( $sign =~ /-/ )
  {
    $time *= -1;
  }

  while (<STDIN>)
  {
    # 00:01:09,040 --> 00:01:11,713
    if ( /(\d\d):(\d\d):(\d\d),(\d+)\s+-->\s+(\d\d):(\d\d):(\d\d),(\d+)/ )
    {
      my ($sh,$sm,$ss,$su,$eh,$em,$es,$eu) = ($1,$2,$3,$4,$5,$6,$7,$8,$9);

      my $s = ($su + ($ss * $scales{'s'}) + ($sm * $scales{'m'}) + ($sh * $scales{'h'})) + $time;
      my $e = ($eu + ($es * $scales{'s'}) + ($em * $scales{'m'}) + ($eh * $scales{'h'})) + $time;

      my $rt = 0;
      $sh    = int($s/$scales{'h'});
      $rt   += ($sh * $scales{'h'});

      $sm    = int(($s - $rt) / $scales{'m'});
      $rt   += ($sm * $scales{'m'});

      $ss    = int(($s - $rt) / $scales{'s'});
      $rt   += ($ss * $scales{'s'});

      $su    = ($s - $rt);

      $rt    = 0;
      $eh    = int($e/$scales{'h'});
      $rt   += ($eh * $scales{'h'});

      $em    = int(($e - $rt) / $scales{'m'});
      $rt   += ($em * $scales{'m'});

      $es    = int(($e - $rt) / $scales{'s'});
      $rt   += ($es * $scales{'s'});

      $eu    = ($e - $rt);

      printf "%02d:%02d:%02d,%03d --> %02d:%02d:%02d,%03d\n", $sh,$sm,$ss,$su,$eh,$em,$es,$eu;
    }
    else
    {
      print $_;
    }
  }
}
else
{
  print "You need to specify time offset\n";
}
